# Mapping ports to airports

In [41]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
ports = pd.read_csv('../curated/ports_clean.csv')

In [11]:
ports.head()

port                     port_name                 port_city port_state  \
0  ALC                     ALCAN, AK                     ALCAN         AK   
1  ANC                 ANCHORAGE, AK                 ANCHORAGE         AK   
2  BAR  BAKER AAF - BAKER ISLAND, AK  BAKER AAF - BAKER ISLAND         AK   
3  DAC             DALTONS CACHE, AK             DALTONS CACHE         AK   
4  PIZ    DEW STATION PT LAY DEW, AK    DEW STATION PT LAY DEW         AK   

  port_state_name  
0          Alaska  
1          Alaska  
2          Alaska  
3          Alaska  
4          Alaska

In [49]:
airports = pd.read_csv('../curated/us_international_airports.csv')

In [5]:
airports.head()

ident           type                                name  elevation_ft  \
0   00A       heliport                   Total Rf Heliport          11.0   
1  00AA  small_airport                Aero B Ranch Airport        3435.0   
2  00AK  small_airport                        Lowell Field         450.0   
3  00AL  small_airport                        Epps Airpark         820.0   
4  00AR         closed  Newport Hospital & Clinic Heliport         237.0   

  continent iso_country iso_region  municipality gps_code iata_code  \
0       NaN          US      US-PA      Bensalem      00A       NaN   
1       NaN          US      US-KS         Leoti     00AA       NaN   
2       NaN          US      US-AK  Anchor Point     00AK       NaN   
3       NaN          US      US-AL       Harvest     00AL       NaN   
4       NaN          US      US-AR       Newport      NaN       NaN   

  local_code                            coordinates state  
0        00A     -74.93360137939453, 40.07080078125    PA  
1       00AA                 -101.473911, 38.704022    KS  
2       00AK            -151.695999146, 59.94919968    AK  
3       00AL  -86.77030181884766, 34.86479949951172    AL  
4        NaN                    -91.254898, 35.6087    AR

Treat common airport terms as stopwords, because they can be wrongly matched:

In [271]:
def stop_words(df):
    return df.iloc[:100,0].to_list()

In [272]:
airport_terms_set = airport_terms.pipe(stop_words)

In [274]:
def airport_corpus(row):
    return f"{row['name']} {row['municipality']}"

In [275]:
def port_corpus(row):
    return row['port_city']

In [276]:
def calc_corpus(df, func):
    return df.assign(corpus=df.apply(axis=1, func=func))

In [277]:
def row_bag(row):
    vectorizer = CountVectorizer(stop_words='english')
    vectorizer.fit_transform([row['corpus']])
    return set(vectorizer.get_feature_names()).difference(airport_terms_set)

In [278]:
def calc_bags(df):
    return df.assign(bag=df.apply(axis=1, func=row_bag))

In [279]:
%%time
airport_bags = (
    airports
    .pipe(calc_corpus, airport_corpus)
    .pipe(calc_bags)
)

CPU times: user 10.9 s, sys: 47.1 ms, total: 11 s
Wall time: 11 s


In [280]:
airport_bags.head(1)

ident      type               name  elevation_ft continent iso_country  \
0   00A  heliport  Total Rf Heliport          11.0       NaN          US   

  iso_region municipality gps_code iata_code local_code  \
0      US-PA     Bensalem      00A       NaN        00A   

                          coordinates state                      corpus  \
0  -74.93360137939453, 40.07080078125    PA  Total Rf Heliport Bensalem   

                     bag  
0  {bensalem, total, rf}

In [281]:
%%time
port_bags = (
    ports
    .pipe(calc_corpus, port_corpus)
    .pipe(calc_bags)
)

CPU times: user 289 ms, sys: 14.6 ms, total: 303 ms
Wall time: 291 ms


In [282]:
port_bags.head(1)

port  port_name port_city port_state port_state_name corpus      bag
0  ALC  ALCAN, AK     ALCAN         AK          Alaska  ALCAN  {alcan}

In [283]:
def cross_bags(df):
    return df.merge(port_bags, left_on='state', right_on='port_state', how='inner')

In [284]:
%%time
cross = (
    airport_bags
    .pipe(cross_bags)
)

CPU times: user 137 ms, sys: 31.1 ms, total: 168 ms
Wall time: 167 ms


In [285]:
cross

ident           type                                name  elevation_ft  \
0        00A       heliport                   Total Rf Heliport          11.0   
1        00A       heliport                   Total Rf Heliport          11.0   
2        00A       heliport                   Total Rf Heliport          11.0   
3        00A       heliport                   Total Rf Heliport          11.0   
4        00A       heliport                   Total Rf Heliport          11.0   
...      ...            ...                                 ...           ...   
354197  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   
354198  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   
354199  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   
354200  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   
354201  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   

       continent iso_country iso_region            municipality gps_code  \
0            NaN          US      US-PA                Bensalem      00A   
1            NaN          US      US-PA                Bensalem      00A   
2            NaN          US      US-PA                Bensalem      00A   
3            NaN          US      US-PA                Bensalem      00A   
4            NaN          US      US-PA                Bensalem      00A   
...          ...         ...        ...                     ...      ...   
354197       NaN          VI     VI-U-A  Christiansted St Croix     VI32   
354198       NaN          VI     VI-U-A  Christiansted St Croix     VI32   
354199       NaN          VI     VI-U-A  Christiansted St Croix     VI32   
354200       NaN          VI     VI-U-A  Christiansted St Croix     VI32   
354201       NaN          VI     VI-U-A  Christiansted St Croix     VI32   

       iata_code local_code                            coordinates state  \
0            NaN        00A     -74.93360137939453, 40.07080078125    PA   
1            NaN        00A     -74.93360137939453, 40.07080078125    PA   
2            NaN        00A     -74.93360137939453, 40.07080078125    PA   
3            NaN        00A     -74.93360137939453, 40.07080078125    PA   
4            NaN        00A     -74.93360137939453, 40.07080078125    PA   
...          ...        ...                                    ...   ...   
354197       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   
354198       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   
354199       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   
354200       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   
354201       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   

                                                 corpus_x  \
0                              Total Rf Heliport Bensalem   
1                              Total Rf Heliport Bensalem   
2                              Total Rf Heliport Bensalem   
3                              Total Rf Heliport Bensalem   
4                              Total Rf Heliport Bensalem   
...                                                   ...   
354197  Christiansted Harbor Seaplane Base Christianst...   
354198  Christiansted Harbor Seaplane Base Christianst...   
354199  Christiansted Harbor Seaplane Base Christianst...   
354200  Christiansted Harbor Seaplane Base Christianst...   
354201  Christiansted Harbor Seaplane Base Christianst...   

                         bag_x port              port_name          port_city  \
0        {bensalem, total, rf}  ERI               ERIE, PA               ERIE   
1        {bensalem, total, rf}  MDT         HARRISBURG, PA         HARRISBURG   
2        {bensalem, total, rf}  HSB       HARRISONBURG, PA       HARRISONBURG   
3        {bensalem, total, rf}  PHI       PHILADELPHIA, PA       PHILADELPHIA   
4        {bensalem, total, rf}  PIT          PITTSBURG, PA          PI

In [286]:
def jaccard(row):
    set1 = row['bag_x']
    set2 = row['bag_y']
    num = len(set1.intersection(set2))
    den = len(set1.union(set2))
    if den == 0:
        return 0
    else:
        return num / den

In [287]:
def cross_jaccard(df):
    return df.assign(jaccard=df.apply(axis=1, func=jaccard))

In [288]:
%%time
distances = cross.pipe(cross_jaccard)

CPU times: user 3.37 s, sys: 88.2 ms, total: 3.46 s
Wall time: 3.46 s


In [289]:
distances

ident           type                                name  elevation_ft  \
0        00A       heliport                   Total Rf Heliport          11.0   
1        00A       heliport                   Total Rf Heliport          11.0   
2        00A       heliport                   Total Rf Heliport          11.0   
3        00A       heliport                   Total Rf Heliport          11.0   
4        00A       heliport                   Total Rf Heliport          11.0   
...      ...            ...                                 ...           ...   
354197  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   
354198  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   
354199  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   
354200  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   
354201  VI32  seaplane_base  Christiansted Harbor Seaplane Base           NaN   

       continent iso_country iso_region            municipality gps_code  \
0            NaN          US      US-PA                Bensalem      00A   
1            NaN          US      US-PA                Bensalem      00A   
2            NaN          US      US-PA                Bensalem      00A   
3            NaN          US      US-PA                Bensalem      00A   
4            NaN          US      US-PA                Bensalem      00A   
...          ...         ...        ...                     ...      ...   
354197       NaN          VI     VI-U-A  Christiansted St Croix     VI32   
354198       NaN          VI     VI-U-A  Christiansted St Croix     VI32   
354199       NaN          VI     VI-U-A  Christiansted St Croix     VI32   
354200       NaN          VI     VI-U-A  Christiansted St Croix     VI32   
354201       NaN          VI     VI-U-A  Christiansted St Croix     VI32   

       iata_code local_code                            coordinates state  \
0            NaN        00A     -74.93360137939453, 40.07080078125    PA   
1            NaN        00A     -74.93360137939453, 40.07080078125    PA   
2            NaN        00A     -74.93360137939453, 40.07080078125    PA   
3            NaN        00A     -74.93360137939453, 40.07080078125    PA   
4            NaN        00A     -74.93360137939453, 40.07080078125    PA   
...          ...        ...                                    ...   ...   
354197       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   
354198       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   
354199       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   
354200       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   
354201       SSB       VI32  -64.70490264892578, 17.74720001220703    VI   

                                                 corpus_x  \
0                              Total Rf Heliport Bensalem   
1                              Total Rf Heliport Bensalem   
2                              Total Rf Heliport Bensalem   
3                              Total Rf Heliport Bensalem   
4                              Total Rf Heliport Bensalem   
...                                                   ...   
354197  Christiansted Harbor Seaplane Base Christianst...   
354198  Christiansted Harbor Seaplane Base Christianst...   
354199  Christiansted Harbor Seaplane Base Christianst...   
354200  Christiansted Harbor Seaplane Base Christianst...   
354201  Christiansted Harbor Seaplane Base Christianst...   

                         bag_x port              port_name          port_city  \
0        {bensalem, total, rf}  ERI               ERIE, PA               ERIE   
1        {bensalem, total, rf}  MDT         HARRISBURG, PA         HARRISBURG   
2        {bensalem, total, rf}  HSB       HARRISONBURG, PA       HARRISONBURG   
3        {bensalem, total, rf}  PHI       PHILADELPHIA, PA       PHILADELPHIA   
4        {bensalem, total, rf}  PIT          PITTSBURG, PA          PI

In [290]:
def max_port_similarities(df):
    return df.groupby('port').max('jaccard')

In [291]:
%%time
max_similarities = (
    distances
    .pipe(max_port_similarities)
)

CPU times: user 79.7 ms, sys: 22.2 ms, total: 102 ms
Wall time: 100 ms


In [292]:
max_similarities

elevation_ft   jaccard
port                        
48Y         1799.0  0.500000
5KE         5742.0  1.000000
ABE         5130.0  0.500000
ABG         2156.0  0.500000
ABQ         8617.0  1.000000
ABS         2156.0  0.500000
ACY         1051.0  1.000000
ADS         5000.0  0.500000
ADT         5000.0  0.200000
ADW         2933.0  0.250000
AFW         5000.0  1.000000
AG0         2418.0  1.000000
AGA          627.0  0.333333
AGM         1735.0  0.500000
AGN         1642.0  0.000000
AGS         2800.0  1.000000
AGU         2340.0  0.333333
AKR         1440.0  1.000000
ALA         8617.0  0.000000
ALB         2380.0  1.000000
ALC         5742.0  0.000000
ALP         1642.0  1.000000
AMB         3102.0  0.000000
ANA         5130.0  1.000000
ANC         5742.0  1.000000
AND         7135.0  0.000000
ANP         8617.0  0.000000
ANT         3102.0  0.500000
ANZ         5000.0  0.000000
APA        12442.0  0.500000
APF          334.0  1.000000
ASE        12442.0  1.000000
AST         6708.0  1.000000
ATB         1440.0  0.500000
ATL         2800.0  0.500000
AUS         5000.0  1.000000
AXB         2380.0  0.500000
BAL         2933.0  0.500000
BAR         5742.0  0.500000
BAU         1799.0  1.000000
BAY         1735.0  0.500000
BBP         5000.0  0.500000
BCK         1825.0  0.000000
BCY         1642.0  0.000000
BDL         1585.0  0.500000
BEA         5000.0  1.000000
BEB         2156.0  0.000000
BED         2102.0  0.666667
BEE         2156.0  0.250000
BEL         5130.0  1.000000
BFL         7135.0  1.000000
BGC         1585.0  1.000000
BGM         1825.0  1.000000
BHM         1825.0  0.500000
BHX         1692.0  0.500000
BIL         7580.0  1.000000
BLA         5130.0  1.000000
BLF         4792.0  0.500000
BLI         5130.0  1.000000
BLT         7135.0  0.285714
BOA         5000.0  0.250000
BOC          334.0  0.000000
BOI         7920.0  0.400000
BOO         1825.0  0.500000
BOS         2102.0  1.000000
BQN         2340.0  0.000000
BRG         2156.0  1.000000
BRO         5000.0  0.500000
BRU         2800.0  0.333333
BTC         5000.0  0.000000
BTM         7580.0  1.000000
BTN          700.0  1.000000
BUF         2380.0  1.000000
BUR         7135.0  0.500000
BWA         5130.0  0.250000
BWM         1825.0  0.000000
BYO         1051.0  0.333333
BZN         7580.0  1.000000
CAE         1250.0  0.500000
CAK         1440.0  1.000000
CAL         7135.0  1.000000
CAN          334.0  0.666667
CAO         7135.0  0.000000
CAP         2380.0  0.666667
CAR         1799.0  0.000000
CDD         8617.0  0.000000
CHA          125.0  0.666667
CHF         7580.0  0.000000
CHI         1065.0  0.500000
CHL         1250.0  1.000000
CHM         2380.0  0.000000
CHO         3793.0  1.000000
CHR          125.0  0.500000
CHS         4792.0  1.000000
CHT         2380.0  0.000000
CID         1538.0  0.750000
CIN         1440.0  0.500000
CLA         2380.0  0.500000
CLE         1440.0  0.500000
CLK         4792.0  0.500000
CLM         1440.0  1.000000
CLS         1825.0  1.000000
CLT         4826.0  0.500000
CNA         2156.0  0.000000
CNC         2380.0  0.250000
CNH         2380.0  0.250000
CNJ         1051.0  0.500000
COB         1825.0  0.000000
COL         8617.0  1.000000
COO         6708.0  1.000000
COS        12442.0  1.000000
CRA         1799.0  0.500000
CRB         1825.0  1.000000
CRL         8617.0  0.333333
CRP         5000.0  1.000000
CRU          125.0  0.500000
CRY         3102.0  0.000000
CSP         8803.0  1.000000
CTB         7580.0  1.000000
CUR         5130.0  0.333333
CUT         7580.0  1.000000
DAA         3793.0  0.250000
DAB          334.0  1.000000
DAC         5742.0  0.000000
DAL         5000.0  1.000000
DEN        12442.0  1.000000
DER         2156.0  0.000000
DET         1642.0  1.000000
DLB         7580.0  0.666667
DLR         5000.0  1.000000
DLV         2156.0  0.000000
DNA         5000.0  0.000000
DNM         8617.0  1.000000
DNS         3102.0  0.333333
DOU         7055.0  1.000000
DOV          595.0  0.500000
DPA 

In [293]:
def merge_similarities(df):
    on = ['port', 'jaccard']
    return (
        df
        .drop(columns=['elevation_ft'])
        .reset_index()
        .merge(distances, left_on=on, right_on=on, how='inner')
    )

In [294]:
%%time
matches = max_similarities.pipe(merge_similarities)

CPU times: user 200 ms, sys: 38.1 ms, total: 238 ms
Wall time: 237 ms


In [295]:
pd.set_option('display.max_columns', None)

In [296]:
def remove_unmatched(df):
    return df[df['jaccard'] > 0]

In [297]:
def same_state(df):
    return df[df['state'] == df['port_state']]

In [298]:
pd.set_option('display.max_rows', 3000)

In [299]:
matches.head()

port  jaccard ident            type  \
0  48Y      0.5   48Y   small_airport   
1  5KE      1.0   5KE   seaplane_base   
2  5KE      1.0  PAKT  medium_airport   
3  ABE      0.5  94WA   small_airport   
4  ABE      0.5  WT00        heliport   

                                       name  elevation_ft continent  \
0            Piney Pinecreek Border Airport        1078.0       NaN   
1            Ketchikan Harbor Seaplane Base           NaN       NaN   
2           Ketchikan International Airport          89.0       NaN   
3               Wishkah River Ranch Airport          36.0       NaN   
4  Grays Harbor Community Hospital Heliport         700.0       NaN   

  iso_country iso_region municipality gps_code iata_code local_code  \
0          US      US-MN    Pinecreek      48Y       NaN        48Y   
1          US      US-AK    Ketchikan      NaN       WFB        5KE   
2          US      US-AK    Ketchikan     PAKT       KTN        KTN   
3          US      US-WA     Aberdeen     94WA       NaN       94WA   
4          US      US-WA     Aberdeen     WT00       NaN       WT00   

                               coordinates state  \
0    -95.98259735107422, 48.99959945678711    MN   
1                   -131.677002, 55.349899    AK   
2                -131.7140045, 55.35559845    AK   
3  -123.77400207519531, 47.084800720214844    WA   
4                   -123.847139, 46.979706    WA   

                                            corpus_x  \
0           Piney Pinecreek Border Airport Pinecreek   
1           Ketchikan Harbor Seaplane Base Ketchikan   
2          Ketchikan International Airport Ketchikan   
3               Wishkah River Ranch Airport Aberdeen   
4  Grays Harbor Community Hospital Heliport Aberdeen   

                        bag_x                  port_name  \
0  {pinecreek, piney, border}  PINECREEK BORDER ARPT, MN   
1                 {ketchikan}              KETCHIKAN, AK   
2                 {ketchikan}              KETCHIKAN, AK   
3         {wishkah, aberdeen}               ABERDEEN, WA   
4           {grays, aberdeen}               ABERDEEN, WA   

               port_city port_state port_state_name               corpus_y  \
0  PINECREEK BORDER ARPT         MN       Minnesota  PINECREEK BORDER ARPT   
1              KETCHIKAN         AK          Alaska              KETCHIKAN   
2              KETCHIKAN         AK          Alaska              KETCHIKAN   
3               ABERDEEN         WA      Washington               ABERDEEN   
4               ABERDEEN         WA      Washington               ABERDEEN   

                       bag_y  
0  {pinecreek, arpt, border}  
1                {ketchikan}  
2                {ketchikan}  
3                 {aberdeen}  
4                 {aberdeen}

In [302]:
(
    matches
    .pipe(remove_unmatched)
    #.pipe(same_state)
    [['state', 'port', 'port_name', 'municipality', 'name', 'jaccard']]
    #[['state', 'port', 'name']]
    #.groupby(['state', 'port']).count()
    .sort_values('jaccard', ascending=False)
)

state port                          port_name  \
30081    CA  LNB                     LONG BEACH, CA   
18805    ND  FAR                          FARGO, ND   
30090    CA  LOS                    LOS ANGELES, CA   
30089    CA  LOS                    LOS ANGELES, CA   
30087    WA  LON                       LONGVIEW, WA   
30083    NM  LOB                      LORDSBURG, NM   
1        AK  5KE                      KETCHIKAN, AK   
27803    LA  LKC                   LAKE CHARLES, LA   
27802    LA  LKC                   LAKE CHARLES, LA   
27798    HI  LIH                          LIHUE, HI   
27797    AR  LIA                    LITTLE ROCK, AR   
27796    UT  LGU          CACHE AIRPORT - LOGAN, UT   
27795    KY  LEX         BLUE GRASS - LEXINGTON, KY   
27794    KY  LEX         BLUE GRASS - LEXINGTON, KY   
27125    FL  LEE     LEESBURG MUNICIPAL AIRPORT, FL   
27124    FL  LEE     LEESBURG MUNICIPAL AIRPORT, FL   
27123    NH  LEB                        LEBANON, NH   
27119    NM  LAS                     LAS CRUCES, NM   
27118    NM  LAS                     LAS CRUCES, NM   
27117    TX  LAR                         LAREDO, TX   
27116    TX  LAR                         LAREDO, TX   
26546    LA  LAK                   LAKE CHARLES, LA   
26545    LA  LAK                   LAKE CHARLES, LA   
25964    FL  KEY                       KEY WEST, FL   
25963    AK  KET                      KETCHIKAN, AK   
25962    AK  KET                      KETCHIKAN, AK   
25961    MO  KAN                    KANSAS CITY, MO   
25960    MO  KAN                    KANSAS CITY, MO   
25628    AK  JUN                         JUNEAU, AK   
30091    KY  LOU                     LOUISVILLE, KY   
30092    TX  LRN                   LAREDO NORTH, TX   
30093    TX  LRN                   LAREDO NORTH, TX   
35451    FL  MIA                          MIAMI, FL   
37061    SC  MYR                   MYRTLE BEACH, SC   
36502    TX  MRS                          MARFA, TX   
35830    MI  MRC                    MARINE CITY, MI   
35725    AL  MOB                         MOBILE, AL   
35724    WI  MNW                      MANITOWOC, WI   
35723    ND  MND                          MINOT, ND   
35722    ND  MND                          MINOT, ND   
35721    ND  MND                          MINOT, ND   
35720    NJ  MMU                     MORRISTOWN, NJ   
35719    NJ  MMU                     MORRISTOWN, NJ   
35718    LA  MLU                         MONROE, LA   
35713    FL  MLB                      MELBOURNE, FL   
35450    FL  MIA                          MIAMI, FL   
30095    ME  LUB                          LUBEC, ME   
35449    FL  MIA                          MIAMI, FL   
35448    FL  MIA                          MIAMI, FL   
35436    TN  MEM                        MEMPHIS, TN   
35429    PA  MDT                     HARRISBURG, PA   
35428    PA  MDT                     HARRISBURG, PA   
32348    TX  MAR                          MARFA, TX   
30999    TX  MAF                ODESSA REGIONAL, TX   
30790    WA  LYN                         LYNDEN, WA   
30458    NV  LVG                      LAS VEGAS, NV   
30457    NV  LVG                      LAS VEGAS, NV   
30456    NV  LVG                      LAS VEGAS, NV   
30455    NV  LVG                      LAS VEGAS, NV   
25627    AK  JUN                         JUNEAU, AK   
25555    FL  JAC                   JACKSONVILLE, FL   
25554    FL  JAC                   JACKSONVILLE, FL   
19830    ME  FTK                      FORT KENT, ME   
19861    MI  GRP                   GRAND RAPIDS, MI   
19858    ND  GRF                    GRAND FORKS, ND   
19857    ND  GRF                    GRAND FORKS, ND   
19856    MT  GRE                    GREAT FALLS, MT   
19855    MT  GRE                    GREAT FALLS, MT   
19854    MT  GRE                    GREAT FALLS, MT   
19840    MA  GLO                     GLOUCESTER, MA   
19836    SC  GEO                     GEORGETOWN, SC   
19835    IN  GAR                           GAR

This are some of those matches that would have been hard with my previous methods:
```
49115	FL	SRQ	BRADENTON - SARASOTA, FL	Sarasota/Bradenton	Sarasota Bradenton International Airport	1.000000

25557	PR	JCP	CULEBRA - BENJAMIN RIVERA, PR	Culebra Island	Benjamin Rivera Noriega Airport	0.750000

312	AK	PIZ	DEW STATION PT LAY DEW, AK	Point Lay	Point Lay LRRS Airport	0.250000

51	ID	BOI	AIR TERM. (GOWEN FLD) BOISE, ID	Boise	Boise Air Terminal/Gowen Field	0.400000
```

There are some false positives, some of the matches with jaccard similarity 0.25 are bad, but others are correct.

In [305]:
(
    matches
    .pipe(remove_unmatched)
    #.pipe(same_state)
)['port'].drop_duplicates().shape

(428,)

Lets get one match for each port:
- favor larger airports and those that are likely to be international
- do this by projecting airport types to ordinals, and an "international" flag
- the latter is determined by whether that term appears in the name, it is not surefire given that there are exceptions (such as Detroit's largest airports)
- sort by (international, type) descending, group by (port) and get the first

In [325]:
airports['type'].drop_duplicates()

0              heliport
1         small_airport
4                closed
36        seaplane_base
1329        balloonport
6180     medium_airport
13507     large_airport
Name: type, dtype: object

In [328]:
airport_sizes = {   
    'closed': 0,
    'balloonport': 1,
    'seaplane_base': 2,
    'heliport': 3,
    'small_airport': 4,
    'medium_airport': 5,
    'large_airport': 6
}

In [330]:
def airport_type_to_size(df):
    return df.assign(size=df['type'].replace(airport_sizes))

In [334]:
def airport_international_flag(df):
    return (
        df
        .assign(
            international=df['name'].str.lower().str.contains('international')
        )
    )

In [352]:
def one_match(df):
    return (
        df.
        sort_values(
            ['port', 'international', 'jaccard', 'size'], 
            ascending=[True, False, False, False]
        )
        .groupby('port').first().reset_index()
    )

In [356]:
def save_port_to_airports_mapping(df):
    (
        df
        .sort_values(['port'])
        [['port','ident']]
    ).to_csv('../curated/port_airports.csv', index=False)

In [357]:
(
    matches
    .pipe(remove_unmatched)
    .pipe(airport_type_to_size)
    .pipe(airport_international_flag)
    .pipe(one_match)
    #[['state', 'port', 'port_name', 'municipality', 'name', 'jaccard']]
    .sort_values(['state', 'municipality'])
)

port   jaccard    ident            type  \
20   ANC  1.000000     6AK5   small_airport   
115  EGL  1.000000     PAEG   small_airport   
255  MOS  0.333333      MOS   small_airport   
140  FRB  1.000000     PAFA   large_airport   
177  HOM  1.000000     PAHO  medium_airport   
187  HYD  1.000000      4Z7   seaplane_base   
200  JUN  1.000000     PAJN  medium_airport   
1    5KE  1.000000     PAKT  medium_airport   
202  KET  1.000000     PAKT  medium_airport   
268  NIK  0.250000     1AK5        heliport   
31   BAR  0.500000      KPB   seaplane_base   
312  PIZ  0.250000     PPIZ  medium_airport   
289  ORI  0.500000      ORI   small_airport   
368  SKA  1.000000     PAGY   small_airport   
377  SNP  1.000000     PASN  medium_airport   
112  DTH  0.500000     88AK   small_airport   
398  TKI  1.000000      57A   seaplane_base   
421  WRA  1.000000     PAWG  medium_airport   
44   BHX  0.500000     KBHM   large_airport   
182  HSV  0.500000     AL93   small_airport   
253  MOB  1.000000     KMOB   large_airport   
11   AG0  1.000000     09AR        heliport   
215  LIA  1.000000     KORK   small_airport   
342  ROG  0.333333     AR11   small_airport   
107  DOU  1.000000     KDGL   small_airport   
269  NOG  1.000000     KOLS  medium_airport   
307  PHO  1.000000     KPHX   large_airport   
318  POR  0.500000     25AZ   small_airport   
373  SLU  0.500000      44A   small_airport   
403  TUC  1.000000     KTUS   large_airport   
426  YUI  1.000000     05AZ        heliport   
427  YUM  1.000000     05AZ        heliport   
40   BFL  1.000000     KBFL  medium_airport   
60   BUR  0.500000     CA95        heliport   
66   CAL  1.000000     KCXL   small_airport   
49   BLT  0.285714     32CN        heliport   
401  TRV  0.333333     KSUU   large_airport   
141  FRE  1.000000     86CA        heliport   
188  ICP  1.000000     KIPL  medium_airport   
220  LNB  1.000000     30CL        heliport   
226  LOS  1.000000     KLAX   large_airport   
280  OAK  0.500000     KOAK   large_airport   
286  ONT  1.000000     KONT   large_airport   
325  PSP  1.000000     KPSP  medium_airport   
293  OTM  0.333333     24CA        heliport   
338  RIV  1.000000     KRAL  medium_airport   
349  SAC  1.000000     KSMF   large_airport   
372  SLS  1.000000     KSNS  medium_airport   
360  SDP  1.000000     KSAN   large_airport   
364  SFR  1.000000     KSFO   large_airport   
375  SNJ  1.000000     CA33        heliport   
370  SLI  1.000000     KSBP  medium_airport   
371  SLO  1.000000     KSBP  medium_airport   
378  SPC  0.500000     CA52        heliport   
348  SAA  0.666667     87CN        heliport   
388  STO  0.500000     KSCK  medium_airport   
410  VNY  1.000000     KVNY  medium_airport   
24   ASE  1.000000     CO50        heliport   
88   COS  1.000000     KCOS  medium_airport   
101  DEN  1.000000     KDEN   large_airport   
110  DRO  1.000000     KDRO   small_airport   
22   APA  0.500000     CD19        heliport   
41   BGC  1.000000     0CT7        heliport   
164  GRT  0.500000     KGON  medium_airport   
277  NWL  0.500000     KGON  medium_airport   
35   BDL  0.500000     KBDL   large_airport   
169  HAR  1.000000     0CT9        heliport   
402  TST  0.250000     CT22        heliport   
276  NWH  1.000000     CT55        heliport   
414  WAS  0.500000     KIAD   large_airport   
108  DOV  0.500000     KDOV   large_airport   
114  DVD  0.500000     KDOV   large_airport   
418  WLL  1.000000     DE39        heliport   
67   CAN  0.666667     1FL8        heliport   
99   DAB  1.000000     KDAB   large_airport   
304  PEV  1.000000      X01   small_airport   
144  FRN  1.000000     FL84   small_airport   
148  FTL  1.000000     KFXE  medium_airport   
133  FMY  0.500000     KFMY  medium_airport   
137  FPF  1.000000     FD88   small_airport   
155  GNV  0.333333     KGNV  medium_airport   
195  JAC  1.000000     KJAX   large_airport   
203  KEY  1.000000     KEYW  medium_airport   
212  LEE  1.000000     KLEE  medium_airport   
185  HUR 

In [358]:
(
    matches
    .pipe(remove_unmatched)
    .pipe(airport_type_to_size)
    .pipe(airport_international_flag)
    .pipe(one_match)
    .pipe(save_port_to_airports_mapping)
)

In [359]:
pd.read_csv('../curated/port_airports.csv')

port    ident
0    48Y      48Y
1    5KE     PAKT
2    ABE     94WA
3    ABG     VT38
4    ABQ     NM00
5    ABS     VT38
6    ACY     JY28
7    ADS     KADS
8    ADT     84TX
9    ADW     KADW
10   AFW     KAFW
11   AG0     09AR
12   AGA     HI47
13   AGM     3WI0
14   AGS     KAGS
15   AGU     TJBQ
16   AKR     88OI
17   ALB     KALB
18   ALP     KAPN
19   ANA     K74S
20   ANC     6AK5
21   ANT     4NA3
22   APA     CD19
23   APF     KAPF
24   ASE     CO50
25   AST     KAST
26   ATB     8OH0
27   ATL     GA53
28   AUS     KEDC
29   AXB     89NY
30   BAL     KMTN
31   BAR      KPB
32   BAU     KBDE
33   BAY      Y77
34   BBP     94TX
35   BDL     KBDL
36   BEA     KBMT
37   BED     KBED
38   BEE     VT50
39   BEL     KBLI
40   BFL     KBFL
41   BGC     0CT7
42   BGM     KBGR
43   BHM     KBHB
44   BHX     KBHM
45   BIL  US-1095
46   BLA      4W6
47   BLF     KBLF
48   BLI     KBLI
49   BLT     32CN
50   BOA  US-0284
51   BOI     KBOI
52   BOO  US-0441
53   BOS     0MA4
54   BRG     KBTV
55   BRO     KBRO
56   BRU     KBQK
57   BTM      84U
58   BTN     27LA
59   BUF      9G0
60   BUR     CA95
61   BWA     5WA4
62   BYO     2NJ9
63   BZN     KBZN
64   CAE     KCAE
65   CAK     88OI
66   CAL     KCXL
67   CAN     1FL8
68   CAP     NY69
69   CHA     VI22
70   CHI     KMDW
71   CHL     KCHS
72   CHO     KCHO
73   CHR     VI32
74   CHS     WV07
75   CID     KCID
76   CIN     KLUK
77   CLA     28NK
78   CLE     KCLE
79   CLK     WV28
80   CLM     2OI6
81   CLS  US-0935
82   CLT     KCLT
83   CNC  US-0048
84   CNH  US-0048
85   CNJ     K19N
86   COL     0NM0
87   COO     OR49
88   COS     KCOS
89   CRA      CDD
90   CRB     KCAR
91   CRL     KCNM
92   CRP     KCRP
93   CRU      SJF
94   CSP     00WY
95   CTB     KCTB
96   CUR  US-0121
97   CUT     KCTB
98   DAA     KAPH
99   DAB     KDAB
100  DAL      1F7
101  DEN     KDEN
102  DET     5MI0
103  DLB      H28
104  DLR     KDRT
105  DNM     KDMN
106  DNS      S28
107  DOU     KDGL
108  DOV     KDOV
109  DPA     KDPA
110  DRO     KDRO
111  DSM     KDSM
112  DTH     88AK
113  DUL     KDLH
114  DVD     KDOV
115  EGL     PAEG
116  EGP     K5T9
117  ELM     KELZ
118  ELP     KELP
119  ELY     KELO
120  EPM     KEPM
121  EPT     KEPM
122  ERI     KERI
123  EUR     K88M
124  EVE     1WA5
125  FAB     KE35
126  FAJ     PR03
127  FAL      FAL
128  FAR     KD54
129  FAY     NR00
130  FCA     KGPI
131  FER     KR49
132  FLX     KFLX
133  FMY     KFMY
134  FOK  US-0271
135  FOP     64NC
136  FOR     ME28
137  FPF     FD88
138  FPR     FL22
139  FPT     0XA3
140  FRB     PAFA
141  FRE     86CA
142  FRI     1WA9
143  FRK     VI01
144  FRN     FL84
145  FTF     ME00
146  FTH      4E9
147  FTK  US-0744
148  FTL     KFXE
149  FWA     WN53
150  GAL     XA73
151  GAR     IN78
152  GEO     KGGE
153  GGW     KGGW
154  GLO     MA42
155  GNV     KGNV
156  GPM     MN81
157  GPT     KGPT
158  GRB     88WI
159  GRE     KGTF
160  GRF     KGFK
161  GRO     KONZ
162  GRP     8MI1
163  GRR     20SC
164  GRT     KGON
165  GSO     KGSO
166  GSP     25SC
167  GTR     KGTR
168  GUL     MS17
169  HAR     0CT9
170  HEF     51VA
171  HEL     KHLN
172  HHW     HI38
173  HIG     05VT
174  HIO     KHIO
175  HLG     KHRL
176  HMM     4II5
177  HOM     PAHO
178  HON     KHON
179  HOP     7VA3
180  HOU     21XS
181  HPN     KHPN
182  HSV     AL93
183  HTM     KHUL
184  HUM   PR-HUC
185  HUR     KHRT
186  HVR     KHVR
187  HYD      4Z7
188  ICP     KIPL
189  ICT     KLBL
190  IDA     KIDA
191  IND     6TA9
192  INP     KIND
193  ISB     KPIL
194  ISL     KPZQ
195  JAC     KJAX
196  JAN     4MS6
197  JCP     TJCP
198  JER     77NJ
199  JKM      59B
200  JUN     PAJN
201  KAN     KMCI
202  KET     PAKT
203  KEY     KEYW
204  KOA     PHKO
205  LAG     KLGA
206  LAK     KLCH
207  LAR     KLRD
208  LAS     KLRU
209  LAU      69S
210  LCB     KLRD
211  LEB     KLEB
212  LEE     KLEE
213  LEX     KLEX
214  LGU     KLGU
215  LIA     KORK
216  LIH     PHLI
217  LIM     ME16
218  LIN     60MN
219  LKC     KLCH
220  LNB     30CL
221  LND

See how many immigration records can be matched to airports:

In [361]:
port_airports = (
    matches
    .pipe(remove_unmatched)
    .pipe(airport_type_to_size)
    .pipe(airport_international_flag)
    .pipe(one_match)
)

In [364]:
i94 = pd.read_csv('../../immigration_data_sample.csv')

There are 962 air arrivals out of 1000:

In [365]:
def only_air(df):
    return df[df['i94mode'] == 1]

In [370]:
(
    i94
    .pipe(only_air)
)

Unnamed: 0      cicid   i94yr  i94mon  i94cit  i94res i94port  arrdate  \
0       2027561  4084316.0  2016.0     4.0   209.0   209.0     HHW  20566.0   
1       2171295  4422636.0  2016.0     4.0   582.0   582.0     MCA  20567.0   
2        589494  1195600.0  2016.0     4.0   148.0   112.0     OGG  20551.0   
3       2631158  5291768.0  2016.0     4.0   297.0   297.0     LOS  20572.0   
5        721257  1481650.0  2016.0     4.0   577.0   577.0     ATL  20552.0   
..          ...        ...     ...     ...     ...     ...     ...      ...   
995     2117909  4288772.0  2016.0     4.0   135.0   135.0     LVG  20567.0   
996     1463022  2947585.0  2016.0     4.0   261.0   261.0     PSP  20560.0   
997     1414569  2883298.0  2016.0     4.0   111.0   111.0     MIA  20560.0   
998     1094181  2264857.0  2016.0     4.0   582.0   582.0     ATL  20556.0   
999     2271807  4654865.0  2016.0     4.0   687.0   687.0     MIA  20568.0   

     i94mode i94addr  depdate  i94bir  i94visa  count  dtadfile visapost  \
0        1.0      HI  20573.0    61.0      2.0    1.0  20160422      NaN   
1        1.0      TX  20568.0    26.0      2.0    1.0  20160423      MTR   
2        1.0      FL  20571.0    76.0      2.0    1.0  20160407      NaN   
3        1.0      CA  20581.0    25.0      2.0    1.0  20160428      DOH   
5        1.0      GA  20606.0    51.0      2.0    1.0  20160408      NaN   
..       ...     ...      ...     ...      ...    ...       ...      ...   
995      1.0      NV  20572.0    32.0      2.0    1.0  20160423      NaN   
996      1.0      HI  20567.0    35.0      1.0    1.0  20160416      JDD   
997      1.0      FL  20566.0    39.0      2.0    1.0  20160416      NaN   
998      1.0      WI  20559.0    35.0      1.0    1.0  20160412      MTR   
999      1.0      FL  20578.0    44.0      2.0    1.0  20160424      BNS   

    occup entdepa entdepd  entdepu matflag  biryear   dtaddto gender  insnum  \
0     NaN       G       O      NaN       M   1955.0  07202016      F     NaN   
1     NaN       G       R      NaN       M   1990.0  10222016      M     NaN   
2     NaN       G       O      NaN       M   1940.0  07052016      M     NaN   
3     NaN       G       O      NaN       M   1991.0  10272016      M     NaN   
5     NaN       T       N      NaN       M   1965.0  10072016      M     NaN   
..    ...     ...     ...      ...     ...      ...       ...    ...     ...   
995   NaN       G       O      NaN       M   1984.0  07212016      M     NaN   
996   NaN       G       O      NaN       M   1981.0  10152016      M     NaN   
997   NaN       G       O      NaN       M   1977.0  07142016      M     NaN   
998   NaN       G       O      NaN       M   1981.0  10112016      M     NaN   
999   NaN       G       O      NaN       M   1972.0  10232016      F     NaN   

    airline        admnum  fltno visatype  
0        JL  5.658267e+10  00782       WT  
1       *GA  9.436200e+10  XBLNG       B2  
2        LH  5.578047e+10  00464       WT  
3        QR  9.478970e+10  00739       B2  
5        DL  7.368526e+08    910       B2  
..      ...           ...    ...      ...  
995      VS  5.914065e+10  00043       WT  
996      SV  9.371186e+10  00041       B1  
997      AF  5.627747e+10  00090       WT  
998      EV  9.334035e+10  05510       B1  
999      LA  9.440386e+10  02514       B2  

[962 rows x 29 columns]

In [366]:
def merge_immigration_with_airports(df, how):
    return df.merge(port_airports, left_on='i94port', right_on='port', how=how)

In [373]:
pd.set_option('display.max_rows', 50)

922 could be matched to a port:

In [369]:
(
    i94
    .pipe(only_air)
    .pipe(merge_immigration_with_airports, 'inner')
)

Unnamed: 0      cicid   i94yr  i94mon  i94cit  i94res i94port  arrdate  \
0       2027561  4084316.0  2016.0     4.0   209.0   209.0     HHW  20566.0   
1       1346671  2720247.0  2016.0     4.0   209.0   209.0     HHW  20559.0   
2       2718518  5475279.0  2016.0     4.0   209.0   209.0     HHW  20573.0   
3       2625403  5284360.0  2016.0     4.0   254.0   276.0     HHW  20572.0   
4        688961  1396100.0  2016.0     4.0   209.0   209.0     HHW  20552.0   
..          ...        ...     ...     ...     ...     ...     ...      ...   
917     2834630  5714501.0  2016.0     4.0   148.0   112.0     FMY  20574.0   
918      366458   751810.0  2016.0     4.0   582.0   582.0     OAK  20548.0   
919     1323990  2693162.0  2016.0     4.0   130.0   130.0     OAK  20559.0   
920     1382732  2814946.0  2016.0     4.0   582.0   582.0     ONT  20559.0   
921     2997207  6027626.0  2016.0     4.0   245.0   245.0     SRQ  20569.0   

     i94mode i94addr  depdate  i94bir  i94visa  count  dtadfile visapost  \
0        1.0      HI  20573.0    61.0      2.0    1.0  20160422      NaN   
1        1.0      HI  20563.0    54.0      2.0    1.0  20160415      NaN   
2        1.0      HI  20577.0    39.0      2.0    1.0  20160429      NaN   
3        1.0      HI  20576.0    11.0      2.0    1.0  20160428      NaN   
4        1.0      HI  20556.0    46.0      2.0    1.0  20160408      NaN   
..       ...     ...      ...     ...      ...    ...       ...      ...   
917      1.0      FL  20600.0    37.0      2.0    1.0  20160430      NaN   
918      1.0      CA  20552.0    36.0      2.0    1.0  20160404      GDL   
919      1.0      CA  20566.0    54.0      2.0    1.0  20160415      NaN   
920      1.0      CA      NaN    51.0      2.0    1.0  20160415      CDJ   
921      1.0      GU  20573.0    29.0      2.0    1.0  20160701      NaN   

    occup entdepa entdepd  entdepu matflag  biryear   dtaddto gender  insnum  \
0     NaN       G       O      NaN       M   1955.0  07202016      F     NaN   
1     NaN       G       O      NaN       M   1962.0  07132016      M     NaN   
2     NaN       G       O      NaN       M   1977.0  07272016      M     NaN   
3     NaN       G       O      NaN       M   2005.0  07262016      M     NaN   
4     NaN       G       O      NaN       M   1970.0  07062016      F     NaN   
..    ...     ...     ...      ...     ...      ...       ...    ...     ...   
917   NaN       G       O      NaN       M   1979.0  07282016      M     NaN   
918   NaN       G       O      NaN       M   1980.0  10032016      M     NaN   
919   NaN       G       O      NaN       M   1962.0  07132016      F     NaN   
920   NaN       G     NaN      NaN     NaN   1965.0  10132016      F     NaN   
921   NaN       P       D      NaN       M   1987.0  05062016      F  3890.0   

    airline        admnum  fltno visatype port  jaccard ident            type  \
0        JL  5.658267e+10  00782       WT  HHW      0.5  HI38        heliport   
1        JL  5.621252e+10  00792       WT  HHW      0.5  HI38        heliport   
2        DL  5.945308e+10  00578       WT  HHW      0.5  HI38        heliport   
3        OZ  5.940346e+10  00232       WT  HHW      0.5  HI38        heliport   
4        NH  5.580982e+10  00184       WT  HHW      0.5  HI38        heliport   
..      ...           ...    ...      ...  ...      ...   ...             ...   
917      AB  5.953445e+10  07008       WT  FMY      0.5  KFMY  medium_airport   
918      Y4  9.276826e+10  00990       B2  OAK      0.5  KOAK   large_airport   
919      DY  5.621531e+10  07067       WT  OAK      0.5  KOAK   large_airport   
920      AM  9.355623e+10  00780       B2  ONT      1.0  KONT   large_airport   
921      3U  4.169896e+10  08647       CP  SRQ      1.0  KSRQ   large_airport   

                                           name  elevation_ft continent  \
0           The Queen's Medical Center Heliport         102.0      None   
1           The Queen's Medical Center Heliport         102

Lets look at those that couldn't be matched:

In [382]:
def unmatched_ports(df):
    return (
        df[df['ident'].isnull()]
        ['i94port']
        .drop_duplicates()
    )

In [384]:
ports_unmatched_to_airport = (
    i94
    .pipe(only_air)
    .pipe(merge_immigration_with_airports, 'left')
    .pipe(unmatched_ports)
)

In [385]:
ports_unmatched_to_airport

1      MCA
13     SAI
14     NAS
48     VCV
49     DUB
88     SHA
194    MON
375    TOR
421    MAA
901    NCA
952    HAM
Name: i94port, dtype: object

Lets focus on the port codes of those:
- only one those ports couldn't be matched to a clean port
- the rest are presumably foreign ports which I should have dropped sooner to begin with

In [377]:
ports = pd.read_csv('../curated/ports_clean.csv')

In [386]:
def merge_unmatched_ports(df):
    return df.merge(ports_unmatched_to_airport, left_on='port', right_on='i94port', how='inner')

In [387]:
(
    ports
    .pipe(merge_unmatched_ports)
)

port    port_name port_city port_state port_state_name i94port
0  MCA  MCALLEN, TX   MCALLEN         TX           Texas     MCA

In [389]:
airports[airports['iata_code'] == 'MFE']

ident            type                                   name  \
15146  KMFE  medium_airport  Mc Allen Miller International Airport   

       elevation_ft continent iso_country iso_region municipality gps_code  \
15146         107.0       NaN          US      US-TX     Mc Allen     KMFE   

      iata_code local_code                coordinates state  
15146       MFE        MFE  -98.23860168, 26.17580032    TX

This seems like an important airport, and worth adding manually

- it is also quite clear why it couldn't be matched, "MCALLEN" vs "Mc Allen"
- TODO maybe better to use a different kind of shingle, 1-char n-grams after removing spaces

First confirm that it wasn't matched, to prevent accidental duplicates:

In [390]:
def manually_add_mcallen_airport(df):
    print("TODO")

### common words in airport names

In [187]:
from collections import Counter

In [199]:
airport_bags['bag']

0                          {bensalem, heliport, total, rf}
1                            {aero, leoti, ranch, airport}
2                           {point, lowell, field, anchor}
3                                 {airpark, harvest, epps}
4                    {newport, heliport, hospital, clinic}
                               ...                        
22887    {heliport, waterfront, amalie, thomas, st, cha...
22888              {heliport, reef, frenchman, thomas, st}
22889    {beach, heliport, resort, amalie, stouffer, gr...
22890    {seaplane, base, amalie, harbor, thomas, st, c...
22891    {christiansted, croix, seaplane, base, harbor,...
Name: bag, Length: 22892, dtype: object

In [248]:
def term_frequency(df):
    counter = Counter()
    for bag in df['name'].to_list():
        for term in bag.split(' '):
            counter.update([term.lower()])
    return (
        pd.DataFrame(counter.items(), columns=['term', 'count'])
        .sort_values('count', ascending=False)
    )

In [250]:
airport_terms = (
    airports
    .pipe(term_frequency)
)

In [254]:
airport_terms[:100]

term  count
6            airport  12032
2           heliport   6417
8              field   1996
12          hospital   1551
65         municipal   1256
5              ranch   1216
44            center    936
147           county    876
43           medical    761
77              base    702
126         regional    625
76          seaplane    604
167         memorial    543
50              farm    433
10           airpark    426
219              air    410
64              lake    408
86           landing    356
246         airstrip    319
67            flying    317
348            strip    291
22             creek    288
83            valley    281
339    international    255
41                st    252
48             farms    247
220             park    223
79          airfield    215
13                 &    193
291             city    177
135        community    176
156           health    175
136               of    168
28             river    162
453          private    157
93                mc    156
39           station    145
134           island    138
96             state    136
455              inc    132
569         helistop    132
279             hill    132
71             north    130
178             area    125
68           service    124
114         mountain    124
161              the    122
493             west    120
413             army    117
151          general    117
420              sky    111
326            south    110
223   ultralightport    108
625            acres    103
359               nr     99
436                -     99
367            ridge     98
124        aerodrome     95
158          springs     94
85               bay     93
276           police     88
256            point     82
55              east     77
89                 j     76
746                2     74
1335            fort     74
636         stolport     73
467                s     71
565             port     71
400                a     71
4                  b     70
356                h     68
192                c     68
398                m     68
108              san     68
905            beach     67
1036      university     67
217            smith     65
616              new     65
2331           force     64
360                1     63
324         aviation     63
844              big     61
472        emergency     61
572          johnson     60
264          helipad     59
3               aero     59
701          estates     59
58                 r     58
605                w     58
177       restricted     57
514              and     55
650             john     54
125             view     53
4045       executive     52
208            white     52
824             fire     51
230           harbor     51
127                l     50
599      helicopters     49